# Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

name: pr
on:
  push:
    branches:
      - "pull-request/[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  pr-builder:
    needs:
      - telemetry-setup
      - checks
      - docs-build
      - publish-api-docs
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@main
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
    permissions:
      contents: read
  telemetry-setup:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      OTEL_SERVICE_NAME: "pr-cugraph-docs"
    steps:
      - name: Telemetry setup
        uses: rapidsai/shared-actions/telemetry-dispatch-stash-base-env-vars@main
  checks:
    needs: telemetry-setup
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@main
    with:
      enable_check_generated_files: false
      ignored_pr_jobs: "telemetry-summarize"
    permissions:
      contents: read
  docs-build:
    needs: checks
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@main
    with:
      build_type: pull-request
      node_type: "gpu-l4-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:26.10-latest"
      script: "ci/build_docs.sh"
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  publish-api-docs:
    needs: [docs-build]
    permissions:
      contents: read
      id-token: write
    secrets:
      akamai-access-token: ${{ secrets.NVIDIA_DOCS_AKAMAI_ACCESS_TOKEN }}
      akamai-client-token: ${{ secrets.NVIDIA_DOCS_AKAMAI_CLIENT_TOKEN }}
      akamai-client-secret: ${{ secrets.NVIDIA_DOCS_AKAMAI_CLIENT_SECRET }}
      akamai-emails-to-notify: ${{ secrets.NVIDIA_DOCS_AKAMAI_EMAILS_TO_NOTIFY }}
      akamai-host: ${{ secrets.NVIDIA_DOCS_AKAMAI_HOST }}
      target-aws-access-key-id: ${{ secrets.NVIDIA_DOCS_AWS_ACCESS_KEY_ID }}
      target-aws-region: ${{ secrets.NVIDIA_DOCS_AWS_REGION }}
      target-aws-secret-access-key: ${{ secrets.NVIDIA_DOCS_AWS_SECRET_ACCESS_KEY }}
      target-s3-bucket: ${{ secrets.NVIDIA_DOCS_S3_BUCKET }}
    uses: rapidsai/shared-workflows/.github/workflows/publish-api-docs.yaml@josephine/x-org-619-publish-api-docs-versions-json
    with:
      docs-projects: cugraph
      dry-run: false
      version-map: ${{ vars.VERSION_MAP }}
  telemetry-summarize:
    # This job must use a self-hosted runner to record telemetry traces.
    runs-on: linux-amd64-cpu4
    needs: pr-builder
    if: ${{ vars.TELEMETRY_ENABLED == 'true' && !cancelled() }}
    continue-on-error: true
    steps:
      - name: Telemetry summarize
        uses: rapidsai/shared-actions/telemetry-dispatch-summarize@main
    permissions:
      actions: write
